<?php
/**
 * Template Name: QT Scheduler
 *
 * FisHotel QT Scheduler — pick a method, generate a day-by-day schedule.
 * Reuses window.FISHOTEL_MEDS for per-dose math; method catalog lives in
 * /assets/js/scheduler/qt-scheduler-data.js (window.FISHOTEL_QT_METHODS).
 *
 * @package fishotel-theme
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

get_header();

// Deep-link support: ?tank=<gal>
$initial_tank = isset( $_GET['tank'] ) ? absint( $_GET['tank'] ) : 30;
if ( $initial_tank < 3 )   { $initial_tank = 3; }
if ( $initial_tank > 500 ) { $initial_tank = 500; }
?>
<main id="primary" class="site-main fst-qt-page">
    <div class="fst-qt-wrap" id="fst-root">

        <header class="fst-hero">
            <div class="fst-eyebrow">The Front Desk</div>
            <h1 class="fst-title">QT Scheduler</h1>
            <div class="fst-hairline" aria-hidden="true"></div>
            <p class="fst-intro">Pick a quarantine protocol. We'll build the day-by-day schedule, with brand-specific dosing for your tank.</p>
        </header>

        <!-- Tank volume + temperature + start date inputs -->
        <div class="fst-inputs">
            <div class="fst-input-row fst-input-row--tank">
                <label for="fst-tank" class="fst-input-label">Tank Volume</label>
                <input id="fst-tank" class="fst-tank-slider" type="range" min="3" max="500" step="1" value="<?php echo esc_attr( $initial_tank ); ?>">
                <input id="fst-tank-text" class="fst-tank-text" type="number" min="3" max="500" step="1" value="<?php echo esc_attr( $initial_tank ); ?>" aria-label="Tank volume in gallons">
                <span class="fst-input-unit">gal</span>
            </div>
            <div class="fst-input-row fst-input-row--temp">
                <label for="fst-temp" class="fst-input-label">Tank Temp</label>
                <input id="fst-temp" class="fst-temp-text" type="number" min="60" max="90" step="1" value="77" aria-label="Tank temperature in Fahrenheit">
                <span class="fst-input-unit">°F</span>
            </div>
            <div class="fst-input-row fst-input-row--startdate">
                <label for="fst-start-date" class="fst-input-label">Start Date</label>
                <input id="fst-start-date" class="fst-startdate-input" type="date" aria-label="Day 1 starts on">
            </div>
        </div>

        <!-- Method picker -->
        <div class="fst-section-label">Choose a Method</div>
        <div id="fst-method-grid" class="fst-method-grid"></div>

        <!-- Per-method config panel (params, addons, conflicts, generate button) -->
        <section id="fst-config-panel" class="fst-config-panel" aria-live="polite" style="display:none;"></section>

        <!-- Generated schedule output -->
        <section id="fst-output" class="fst-output" aria-live="polite" style="display:none;"></section>

        <!-- Action footer -->
        <div id="fst-actions" class="fst-actions" style="display:none;">
            <div class="fst-spacer"></div>
            <button type="button" id="fst-print" class="fst-actbtn fst-print-schedule">Print Schedule</button>
            <button type="button" id="fst-ics"   class="fst-actbtn fst-export-ics">Save to Calendar</button>
        </div>

        <!-- Legacy slot — meds + reminders now render inside #fst-output. Hidden by default. -->
        <section id="fst-medlist-wrap" class="fst-medlist-wrap" style="display:none;"></section>

        <p class="fst-disclaimer">
            QT protocols generated by FisHotel reference the Humblefish methodology and the dose math from our medication calculator. Always verify copper with a Hanna HI702. If in doubt, ask FisHotel before dosing.
        </p>

        <div class="fst-print-footer">FisHotel — fishotel.com</div>

    </div>
</main>
<?php
get_footer();
